// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwO29cmIhIUS3NNrAkLWkzPZM0jGdFGZc',
    appId: '1:340881242102:web:96bb387a4b6a0afca4f9d7',
    messagingSenderId: '340881242102',
    projectId: 'smartapp-a6880',
    authDomain: 'smartapp-a6880.firebaseapp.com',
    storageBucket: 'smartapp-a6880.firebasestorage.app',
    measurementId: 'G-8SM65R659S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxy6gzF-nP2hEAwP81T-yoRYQbgg0jCo',
    appId: '1:340881242102:android:e614d32fbea49f66a4f9d7',
    messagingSenderId: '340881242102',
    projectId: 'smartapp-a6880',
    storageBucket: 'smartapp-a6880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCno4t9leI4pAUkn7-WWkMgxRvZlyvGxsc',
    appId: '1:340881242102:ios:bc20331616fa5c56a4f9d7',
    messagingSenderId: '340881242102',
    projectId: 'smartapp-a6880',
    storageBucket: 'smartapp-a6880.firebasestorage.app',
    iosClientId: '340881242102-h2c1s8moqvi1e8kjc88uubrjmd8l62ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitClassifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCno4t9leI4pAUkn7-WWkMgxRvZlyvGxsc',
    appId: '1:340881242102:ios:bc20331616fa5c56a4f9d7',
    messagingSenderId: '340881242102',
    projectId: 'smartapp-a6880',
    storageBucket: 'smartapp-a6880.firebasestorage.app',
    iosClientId: '340881242102-h2c1s8moqvi1e8kjc88uubrjmd8l62ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitClassifier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwO29cmIhIUS3NNrAkLWkzPZM0jGdFGZc',
    appId: '1:340881242102:web:57b7470a7650f7b4a4f9d7',
    messagingSenderId: '340881242102',
    projectId: 'smartapp-a6880',
    authDomain: 'smartapp-a6880.firebaseapp.com',
    storageBucket: 'smartapp-a6880.firebasestorage.app',
    measurementId: 'G-SVK1YBQ8J3',
  );

}